# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'toufik' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for toufik
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'
  pod 'DropDown'
  pod 'SQLite.swift', '~> 0.12.0'

end
